import { Dimensions } from 'react-native';
const W = Dimensions.get('window').width;
export const SIDE = 12;
export const GUTTER = 10;
export const CARD_WIDTH = W - SIDE * 2;
export const H_ASSET = 112;
export const H_SMALL = 88;
export const H_BOX = 150;
export const TILT_ASSET = -12;
export const TILT_SMALL = -10;
export const TILT_BOX = -14;
export const RADIUS = 20;
export const NAV_H = 72;
export const PRESS_SCALE = 0.98;
