name: Android Debug Build

on:
  workflow_dispatch: {}          # 支持手动触发
  push:
    branches: [ main ]           # 或改成你常用的分支

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install JS dependencies
        run: npm ci
        working-directory: apps/mobile

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('apps/mobile/android/**/*.gradle*', 'apps/mobile/android/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 34
          build-tools: "34.0.0"
          ndk: "25.2.9519653"

      - name: Make Gradle wrapper executable
        run: chmod +x android/gradlew
        working-directory: apps/mobile

      - name: Build Debug APK
        run: ./gradlew assembleDebug
        working-directory: apps/mobile/android

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: apps/mobile/android/app/build/outputs/apk/debug/app-debug.apk
