name: Android Debug Build

on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

jobs:
  android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install JS dependencies
        run: npm ci
        working-directory: apps/mobile

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('apps/mobile/android/**/*.gradle*', 'apps/mobile/android/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          components: |
            platform-tools
            platforms;android-34
            build-tools;34.0.0
            ndk;25.2.9519653

      - name: Make Gradle wrapper executable
        run: chmod +x android/gradlew
        working-directory: apps/mobile

      - name: Generate autolinking config
        run: |
          mkdir -p android/build/generated/autolinking
          npx react-native config > android/build/generated/autolinking/autolinking.json
        working-directory: apps/mobile

      - name: Ensure debug keystore
        shell: bash
        run: |
          set -euo pipefail
          KEYSTORE="${HOME}/.android/debug.keystore"
          if [ ! -f "${KEYSTORE}" ]; then
            mkdir -p "$(dirname "${KEYSTORE}")"
            keytool -genkeypair \
              -alias androiddebugkey \
              -keyalg RSA \
              -keysize 2048 \
              -storetype PKCS12 \
              -keystore "${KEYSTORE}" \
              -storepass android \
              -keypass android \
              -validity 10000 \
              -dname "CN=Android Debug,O=Android,C=US"
          fi

      - name: Build Debug APK
        run: ./gradlew assembleDebug --info --stacktrace
        working-directory: apps/mobile/android

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: android-debug-apk
          path: apps/mobile/android/app/build/outputs/apk/debug/app-debug.apk
